Repository RAF-SI-2024/Banka-3-Backend, pull requests merged in 2025-04, with the labels that each got.

#193 DatumiZaOpcije
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ListingDetailsDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Option.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/ListingMapper.java
  stock-service/src/main/java/rs/raf/stock_service/repository/OptionRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/ListingService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/ListingControllerTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/ListingServiceTest.java
Labels: size/L, lgtm, approved

#200 Razni fixovi oko Listinga
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/client/AlphavantageClient.java
  stock-service/src/main/java/rs/raf/stock_service/controller/ForexController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/PortfolioEntryDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/PriceHistoryDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/StockDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Country.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Holiday.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Listing.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/ListingPriceHistory.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/PortfolioEntry.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/ListingMapper.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/TimeSeriesMapper.java
  stock-service/src/main/java/rs/raf/stock_service/repository/ExchangeRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/ListingDailyPriceInfoRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/ListingPriceHistoryRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/OptionRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/PortfolioEntryRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/CountryService.java
  stock-service/src/main/java/rs/raf/stock_service/service/ExchangeService.java
  stock-service/src/main/java/rs/raf/stock_service/service/ForexService.java
  stock-service/src/main/java/rs/raf/stock_service/service/FuturesService.java
  stock-service/src/main/java/rs/raf/stock_service/service/HolidayService.java
  stock-service/src/main/java/rs/raf/stock_service/service/ListingService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OptionService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
  stock-service/src/main/java/rs/raf/stock_service/service/StocksService.java
  stock-service/src/main/java/rs/raf/stock_service/specification/ListingSpecification.java
  stock-service/src/main/resources/application.properties
  stock-service/src/main/resources/exchanges1.csv
  stock-service/src/main/resources/exchanges2.csv
  stock-service/src/main/resources/holidaysUSA.json
  stock-service/src/test/java/rs/raf/stock_service/unit/CountryServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/ListingControllerTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/ListingServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OrderServiceTest.java
  stock-service/src/test/java/unit/PortfolioServiceTest.java
Labels: size/XXL, lgtm, approved

#208 Dodata polja premium i option u OtcOffer entitet
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Option.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/OtcOffer.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/OtcOfferStatus.java
Labels: lgtm, approved, size/M

#207 Doradjeni unit testovi
  user-service/src/test/java/rs/raf/user_service/unit/ActuaryServiceTest.java
  user-service/src/test/java/rs/raf/user_service/unit/AuthServiceTest.java
  user-service/src/test/java/rs/raf/user_service/unit/AuthorizedPersonelServiceTest.java
  user-service/src/test/java/rs/raf/user_service/unit/ClientServiceTest.java
  user-service/src/test/java/rs/raf/user_service/unit/CompanyServiceTest.java
  user-service/src/test/java/rs/raf/user_service/unit/EmployeeServiceTest.java
  user-service/src/test/java/rs/raf/user_service/unit/UserServiceTest.java
  user-service/src/test/java/rs/raf/user_service/unit/VerificationRequestServiceTest.java
Labels: size/XXL, lgtm, approved

#214 Otc entity fixes plus more
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/PublicStockDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/OtcOffer.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/OtcOption.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
  user-service/src/main/java/rs/raf/user_service/domain/entity/Client.java
Labels: lgtm, approved, size/M

#223 Kotlin polish
  user-service-kotlin/pom.xml
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/arrow/EmployeeServiceError.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/ActuaryController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/AuthController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/AuthorizedPersonnelController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/ClientController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/EmployeeController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/UserController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/domain/dto/company/CreateCompanyDto.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/domain/dto/employee/CreateEmployeeDto.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/domain/dto/external/UserResponseDto.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/domain/dto/role/RoleRequestDto.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/external/BankClient.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/external/BankClientFallbackFactory.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/external/FeignClientInterceptor.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/repository/ActivityCodeRepository.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/repository/ActuaryLimitRepository.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/service/ActuaryService.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/service/CompanyService.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/service/EmployeeService.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/controller/ActuaryControllerTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/controller/AuthControllerTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/controller/AuthorizedPersonnelControllerTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/controller/ClientControllerTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/controller/CompanyControllerTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/controller/EmployeeControllerTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/controller/UserControllerTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/domain/TestDataFactory.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/domain/TestRequestData.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/domain/TestResponseData.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/domain/TestUpdateData.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/service/ActuaryServiceTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/service/AuthServiceTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/service/AuthorizedPersonnelServiceTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/service/ClientServiceTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/service/CompanyServiceTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/service/EmployeeServiceTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/service/UserServiceTest.kt
Labels: size/XXL, lgtm, approved

#213 Implementirana kompletna funkcionalnost za klijentske OTC ponude sa D…
  stock-service/src/main/java/rs/raf/stock_service/StockServiceApplication.java
  stock-service/src/main/java/rs/raf/stock_service/client/UserClient.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OtcOfferController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ActuaryDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/CreateOtcOfferDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OtcOfferDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/StockDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/OtcOfferStatus.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OtcOfferMapper.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/StockMapper.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/StockOptionMapper.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/UnauthorizedActionException.java
  stock-service/src/main/java/rs/raf/stock_service/repository/OtcOfferRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/OtcService.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
  stock-service/src/test/java/unit/OtcOfferServiceTest.java
Labels: lgtm, approved, size/XL

#225 Add test orders to bootstrap, fix portfolio tax endpoint
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/controller/PortfolioController.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
Labels: size/L, lgtm, approved

#226 Add otc option endpoint + bootstrap data
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OtcOfferController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OtcOptionDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/OtcOption.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/OtcOptionStatus.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OtcOptionMapper.java
  stock-service/src/main/java/rs/raf/stock_service/repository/OtcOptionRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/OtcService.java
Labels: size/L, lgtm, approved

#222 Uradjen profit za aktuare
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/PaymentServiceTest.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClient.java
  stock-service/src/main/java/rs/raf/stock_service/client/UserClient.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/AccountDetailsDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ConvertDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OrderDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OrderMapper.java
  stock-service/src/main/java/rs/raf/stock_service/repository/OrderRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  user-service/src/main/java/rs/raf/user_service/client/StockClient.java
  user-service/src/main/java/rs/raf/user_service/controller/ActuaryController.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/ActuaryDto.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/OrderDto.java
  user-service/src/main/java/rs/raf/user_service/domain/mapper/ActuaryMapper.java
  user-service/src/main/java/rs/raf/user_service/service/ActuaryService.java
  user-service/src/main/resources/application.properties
  user-service/src/test/java/rs/raf/user_service/unit/ActuaryControllerTest.java
  user-service/src/test/java/rs/raf/user_service/unit/ActuaryServiceTest.java
Labels: size/L, lgtm, approved

#220 Periodicni update cena akcija i forexa (i opcija?) #203
  stock-service/src/main/java/rs/raf/stock_service/StockServiceApplication.java
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OptionDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/StockDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Option.java
  stock-service/src/main/java/rs/raf/stock_service/repository/ListingPriceHistoryRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/OptionRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/PortfolioEntryRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/DataRefreshService.java
  stock-service/src/main/java/rs/raf/stock_service/service/ListingService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OptionService.java
  stock-service/src/main/java/rs/raf/stock_service/service/StockOptionService.java
  stock-service/src/main/java/rs/raf/stock_service/service/StocksService.java
  stock-service/src/main/resources/application.properties
  stock-service/src/test/java/rs/raf/stock_service/unit/StockOptionServiceTest.java
Labels: lgtm, approved, size/XL

#233 Fix set password email url
  email-service/src/main/java/rs/raf/email_service/utils/EmailUtils.java
Labels: lgtm, approved

#231 uradjeno Iskoriscavanje opcije (van OTC) #205
  stock-service/src/main/java/rs/raf/stock_service/StockServiceApplication.java
  stock-service/src/main/java/rs/raf/stock_service/controller/PortfolioController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/UseOptionDto.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/OptionNotEligibleException.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
  stock-service/src/test/java/unit/PortfolioServiceTest.java
Labels: size/L, lgtm, approved

#235 Add listingId to portfolioEntry
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/PortfolioEntryDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/PortfolioMapper.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
Labels: size/XS, lgtm, approved

#236 Dodati testovi za DataRefreshService klasu i neke anotacije u dto-ovima
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ForexPairDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OptionDto.java
  stock-service/src/main/java/rs/raf/stock_service/service/DataRefreshService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/DataRefreshServiceTest.java
Labels: size/L, lgtm, approved

#232 Uradjen portal za porez
  stock-service/src/main/java/rs/raf/stock_service/client/UserClient.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/raf/stock_service/controller/PortfolioController.java
  stock-service/src/main/java/rs/raf/stock_service/controller/TaxController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/UserTaxDto.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
  stock-service/src/main/java/rs/raf/stock_service/service/TaxService.java
  user-service/src/main/java/rs/raf/user_service/controller/ActuaryController.java
  user-service/src/main/java/rs/raf/user_service/service/ActuaryService.java
  user-service/src/main/java/rs/raf/user_service/specification/ClientSearchSpecification.java
Labels: size/L, lgtm, approved

#234 Kreiran endpoint za listu racuna
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AccountServiceTest.java
Labels: lgtm, approved, size/M

#240 Fix importHolidays lazy fetch
  stock-service/src/main/java/rs/raf/stock_service/service/HolidayService.java
Labels: size/XS, lgtm, approved

#246 Uradjene OrderDto izmene #230
  stock-service/src/main/java/rs/raf/stock_service/client/UserClientFallbackFactory.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OrderDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OrderMapper.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OrderServiceTest.java
Labels: size/L, lgtm, approved

#250 [B] Cuvanje account name pri kreiranju
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
Labels: size/XS, lgtm, approved

#253 Endpoint za agente sada vraca i njihove limite itd
  user-service/src/main/java/rs/raf/user_service/controller/ActuaryController.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/AgentDto.java
  user-service/src/main/java/rs/raf/user_service/domain/mapper/ActuaryMapper.java
  user-service/src/main/java/rs/raf/user_service/service/ActuaryService.java
  user-service/src/test/java/rs/raf/user_service/unit/ActuaryControllerTest.java
  user-service/src/test/java/rs/raf/user_service/unit/ActuaryServiceTest.java
Labels: size/L, lgtm, approved

#248 profit za stock i bank
  bank-service/src/main/java/rs/raf/bank_service/controller/ProfitController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/BankProfitResponseDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/ExchangeRate.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Payment.java
  bank-service/src/main/java/rs/raf/bank_service/repository/PaymentRepository.java
  bank-service/src/main/java/rs/raf/bank_service/repository/ProfitRepository.java
  bank-service/src/main/java/rs/raf/bank_service/service/ExchangeRateService.java
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentService.java
  bank-service/src/main/java/rs/raf/bank_service/service/ProfitService.java
  stock-service/src/main/java/rs/raf/stock_service/controller/ProfitController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ActuaryProfitDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/StockProfitResponseDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/repository/OrderRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/ProfitRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/main/java/rs/raf/stock_service/service/ProfitService.java
  stock-service/src/main/resources/application.properties
Labels: size/L, lgtm, approved

#254 Add stop and limit order check on price refresh
  stock-service/src/main/java/rs/raf/stock_service/service/DataRefreshService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/DataRefreshServiceTest.java
Labels: lgtm, approved, size/S

#255 add kubernetes cors
  bank-service/src/main/java/rs/raf/bank_service/configuration/SpringSecurityConfig.java
  stock-service/src/main/java/rs/raf/stock_service/configuration/SpringSecurityConfig.java
  user-service/src/main/java/rs/raf/user_service/configuration/SpringSecurityConfig.java
Labels: size/XS, approved

#260 Add otc option id to dto
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OtcOptionDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OtcOptionMapper.java
Labels: size/XS, lgtm, approved

#247 Iskoriscavanje OTC opcije
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/raf/bank_service/controller/PaymentController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/ExecutePaymentDto.java
  bank-service/src/main/java/rs/raf/bank_service/security/JwtAuthenticationFilter.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentService.java
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClient.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClientFallbackFactory.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OtcController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ExecutePaymentDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/OtcOption.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/OtcOfferStatus.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/InvalidOtcOptionException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/OtcException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/OtcExecutionFailedException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/OtcOptionAlreadyExercisedException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/OtcOptionNotFoundException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/OtcOptionSettlementExpiredException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/OtcRollbackFailedException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/SystemPaymentFailedException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/UnauthorizedOtcAccessException.java
  stock-service/src/main/java/rs/raf/stock_service/repository/OtcOptionRepository.java
  stock-service/src/main/java/rs/raf/stock_service/security/JwtAuthenticationFilter.java
  stock-service/src/main/java/rs/raf/stock_service/service/OtcService.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
  stock-service/src/main/java/rs/raf/stock_service/utils/JwtTokenUtil.java
  user-service/src/main/java/rs/raf/user_service/security/JwtAuthenticationFilter.java
Labels: size/L, lgtm, approved

#263 Add logs to account controller
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
Labels: lgtm, approved

#264 odradjeni taskovi #259
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OtcOptionDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/PortfolioEntryDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/StockOptionDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OtcOptionMapper.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/PortfolioMapper.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/StockOptionMapper.java
  stock-service/src/test/java/rs/raf/stock_service/unit/StockOptionControllerTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/StockOptionServiceTest.java
Labels: lgtm, approved, size/M

#267 Fix
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ListingDto.java
Labels: size/XS, lgtm, approved

#266 Actuary fix kotlin
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/UserServiceKotlinApplication.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/arrow/ActuaryServiceError.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/arrow/VerificationServiceError.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/ActuaryController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/ClientController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/EmployeeController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/UserController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/VerificationRequestController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/domain/dto/actuary_limit/ActuaryResponseDto.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/domain/dto/employee/AgentDto.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/domain/dto/external/OrderDto.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/domain/mapper/EmployeeMapper.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/external/StockClient.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/service/ActuaryService.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/service/VerificationRequestService.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/specification/ClientSearchSpecification.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/specification/EmployeeSearchSpecification.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/swagger/ActuaryApiDoc.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/swagger/VerificationRequestApiDoc.kt
  user-service-kotlin/src/main/resources/application.properties
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/controller/ActuaryControllerTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/controller/VerificationRequestControllerTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/domain/TestDataFactory.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/service/ActuaryServiceTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/service/VerificationRequestServiceTest.kt
Labels: size/XXL, lgtm, approved

#273 Refactor payment notifications and add payment status tracking
  bank-service/src/main/java/rs/raf/bank_service/bootstrap/BootstrapData.java
  bank-service/src/main/java/rs/raf/bank_service/client/StockClient.java
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/CreatePaymentDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/TrackedPaymentNotifyDto.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentCallbackService.java
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentService.java
  bank-service/src/main/java/rs/raf/bank_service/service/TransactionProcessor.java
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClient.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClientFallbackFactory.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OtcController.java
  stock-service/src/main/java/rs/raf/stock_service/controller/TrackedPaymentController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/CreatePaymentDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/TrackedPaymentDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/TrackedPaymentNotifyDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/TrackedPayment.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/TrackedPaymentStatus.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/TrackedPaymentType.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OrderMapper.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/TrackedPaymentMapper.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/OtcAccountNotFoundForBuyerException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/OtcAccountNotFoundForSellerException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/TrackedPaymentNotFoundException.java
  stock-service/src/main/java/rs/raf/stock_service/repository/TrackedPaymentRepository.java
  stock-service/src/main/java/rs/raf/stock_service/security/JwtAuthenticationFilter.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OtcService.java
  stock-service/src/main/java/rs/raf/stock_service/service/TrackedPaymentNotificationService.java
  stock-service/src/main/java/rs/raf/stock_service/service/TrackedPaymentService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OrderServiceTest.java
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/bootstrap/BootstrapData.kt
  user-service/src/main/java/rs/raf/user_service/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/ActuaryDto.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/OrderDto.java
Labels: size/XXL, lgtm, approved

#274 dodato polje ownerName u otcOptionDto #270
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OtcOptionDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OtcOptionMapper.java
  stock-service/src/main/java/rs/raf/stock_service/service/OtcService.java
Labels: lgtm, approved, size/S

#275 Refactor and fix tax process
  bank-service/src/main/java/rs/raf/bank_service/bootstrap/BootstrapData.java
  bank-service/src/main/java/rs/raf/bank_service/controller/PaymentController.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClient.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClientFallbackFactory.java
  stock-service/src/main/java/rs/raf/stock_service/controller/TaxController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/TrackedPayment.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/TrackedPaymentType.java
  stock-service/src/main/java/rs/raf/stock_service/repository/TrackedPaymentRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/TaxService.java
  stock-service/src/main/java/rs/raf/stock_service/service/TrackedPaymentNotificationService.java
  stock-service/src/main/java/rs/raf/stock_service/service/TrackedPaymentService.java
Labels: size/L, lgtm, approved

#276 Add kotlin to docker/cicd
  .prow/build.yaml
  .prow/user-service-kotlin.yaml
  docker-compose.test.yml
  user-service-kotlin/Dockerfile
  user-service-kotlin/pom.xml
Labels: size/L, lgtm, approved

#265 [B] Cuvanje hartija u redisu #241
  docker-compose.local.prod.yml
  docker-compose.prod.yml
  docker-compose.test.yml
  docker-compose.yml
  stock-service/pom.xml
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/configuration/RedisConfig.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ListingFilterDto.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/ListingNotFoundException.java
  stock-service/src/main/java/rs/raf/stock_service/service/DataRefreshService.java
  stock-service/src/main/java/rs/raf/stock_service/service/ListingRedisService.java
  stock-service/src/main/java/rs/raf/stock_service/service/ListingService.java
  stock-service/src/main/resources/application.properties
  stock-service/src/test/java/rs/raf/stock_service/unit/DataRefreshServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/ListingServiceTest.java
Labels: lgtm, approved, size/XL

#278 Add settlement date for futures, add portfolio tax currency conversion
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ListingDetailsDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ListingDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/ListingMapper.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
  stock-service/src/main/java/rs/raf/stock_service/service/TaxService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/ListingServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OrderServiceTest.java
Labels: lgtm, approved, size/M

#249 Usavrsavanje Ordera
  bank-service/src/main/java/rs/raf/bank_service/bootstrap/BootstrapData.java
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AccountServiceTest.java
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClient.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClientFallbackFactory.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/raf/stock_service/controller/PortfolioController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OrderDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/OtcOption.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/PortfolioEntry.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/OrderStatus.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/OtcOptionStatus.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/TrackedPaymentType.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OrderMapper.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OtcOptionMapper.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/PortfolioAmountNotEnoughException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/TransactionNotFoundException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/WrongCurrencyAccountException.java
  stock-service/src/main/java/rs/raf/stock_service/repository/OrderRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/OtcOptionRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OtcService.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
  stock-service/src/main/java/rs/raf/stock_service/service/TrackedPaymentNotificationService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OrderServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OtcOfferServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/PortfolioServiceTest.java
  user-service/src/main/java/rs/raf/user_service/bootstrap/BootstrapData.java
Labels: size/XXL, lgtm, approved

#280 Add deploy job
  .prow/deploy.yaml
Labels: approved, size/S

#281 Fix regex
  .prow/deploy.yaml
Labels: size/XS, approved

#282 Update deploy script
  .prow/deploy.yaml
Labels: approved, size/S

#283 Fix deploy job
  .prow/deploy.yaml
Labels: size/XS, approved

#285 Ispravke sitnica u vezi ordera
  bank-service/src/main/java/rs/raf/bank_service/bootstrap/BootstrapData.java
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentService.java
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClient.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClientFallbackFactory.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/PortfolioEntryDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/OrderStatus.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/PortfolioMapper.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/InsufficientFundsException.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OtcService.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OrderServiceTest.java
Labels: size/L, lgtm, approved

#286 Fix deploy job
  .prow/deploy.yaml
Labels: lgtm, approved

#287 Fix agent limit / fix order sleep + currency bug
  bank-service/src/main/java/rs/raf/bank_service/client/UserClient.java
  bank-service/src/main/java/rs/raf/bank_service/client/UserClientFallbackFactory.java
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/raf/bank_service/controller/PaymentController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/ActuaryLimitDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/ChangeAgentLimitDto.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/AgentLimitExceededException.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/UpdateUsedLimitException.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentService.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClientFallbackFactory.java
  stock-service/src/main/java/rs/raf/stock_service/controller/PortfolioController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/security/JwtAuthenticationFilter.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OtcService.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OrderServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/PortfolioServiceTest.java
  user-service/src/main/java/rs/raf/user_service/controller/ActuaryController.java
  user-service/src/main/java/rs/raf/user_service/controller/AuthController.java
  user-service/src/main/java/rs/raf/user_service/exceptions/EmployeeNotActive.java
  user-service/src/main/java/rs/raf/user_service/service/ActuaryService.java
  user-service/src/main/java/rs/raf/user_service/service/AuthService.java
  user-service/src/main/java/rs/raf/user_service/service/EmployeeService.java
  user-service/src/test/java/rs/raf/user_service/unit/AuthControllerTest.java
Labels: lgtm, approved, size/XL

#288 Fix order simulation + forex only USD + show commission profit in RSD
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Listing.java
  stock-service/src/main/java/rs/raf/stock_service/service/ListingRedisService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/PortfolioServiceTest.java
Labels: size/L, lgtm, approved

#289 Kotlin fix
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/arrow/AuthServiceError.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/ActuaryController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/AuthController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/AuthorizedPersonnelController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/EmployeeController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/domain/dto/actuary_limit/UpdateActuaryLimitDto.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/service/ActuaryService.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/service/AuthService.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/service/EmployeeService.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/swagger/ActuaryApiDoc.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/swagger/EmployeeApiDoc.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/utils/JwtTokenUtil.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/controller/ActuaryControllerTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/service/ActuaryServiceTest.kt
  user-service/src/main/java/rs/raf/user_service/controller/AuthController.java
Labels: lgtm, approved, size/XL

#291 Dodati neki testovi
  stock-service/src/main/java/rs/raf/stock_service/service/ListingService.java
  stock-service/src/main/java/rs/raf/stock_service/service/TaxService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/FuturesServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/ListingRedisServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/ListingServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OtcOfferServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/PortfolioServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/StocksServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/TaxServiceTest.java
Labels: size/XXL, lgtm, approved

#292 More small fixes + kotlin fixes + remove annoying prints
  bank-service/src/main/java/rs/raf/bank_service/security/JwtAuthenticationFilter.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  bank-service/src/main/java/rs/raf/bank_service/service/LoanService.java
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentService.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/ForexPair.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/FuturesContract.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/ListingPriceHistory.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/OtcOffer.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/OtcOption.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/PortfolioEntry.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Stock.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Transaction.java
  stock-service/src/main/java/rs/raf/stock_service/service/OtcService.java
  stock-service/src/main/java/rs/raf/stock_service/service/TaxService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OtcOfferServiceTest.java
  user-service-kotlin/pom.xml
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/domain/dto/employee/AgentDto.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/domain/mapper/EmployeeMapper.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/service/ActuaryService.kt
  user-service/src/main/java/rs/raf/user_service/security/JwtAuthenticationFilter.java
Labels: size/L, lgtm, approved

#279 Data Science
  bank-service/pom.xml
  bank-service/src/main/java/rs/raf/bank_service/bootstrap/BootstrapData.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Account.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Card.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Loan.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/LoanRequest.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Payee.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Payment.java
  data-analysis-service/.env.example
  data-analysis-service/Dockerfile
  data-analysis-service/README.md
  data-analysis-service/app/__init__.py
  data-analysis-service/app/analysis/__init__.py
  data-analysis-service/app/analysis/analytics_router.py
  data-analysis-service/app/analysis/calculations/__init__.py
  data-analysis-service/app/analysis/calculations/churn_risk.py
  data-analysis-service/app/analysis/calculations/client_segmentation.py
  data-analysis-service/app/analysis/calculations/client_value.py
  data-analysis-service/app/analysis/calculations/credit_score.py
  data-analysis-service/app/analysis/calculations/loans.py
  data-analysis-service/app/analysis/calculations/product_usage.py
  data-analysis-service/app/analysis/database.py
  data-analysis-service/app/analysis/init_db.py
  data-analysis-service/app/analysis/models.py
  data-analysis-service/app/analysis/router.py
  data-analysis-service/app/analysis/templates/product-usage.html
  data-analysis-service/app/analysis/visuals/__init__.py
  data-analysis-service/app/analysis/visuals/churn_risk.py
  data-analysis-service/app/analysis/visuals/client_segmentation.py
  data-analysis-service/app/analysis/visuals/client_value.py
  data-analysis-service/app/analysis/visuals/credit_score.py
  data-analysis-service/app/analysis/visuals/loans.py
  data-analysis-service/app/analysis/visuals/product_usage.py
  data-analysis-service/app/analysis/visuals/visualizations.py
  data-analysis-service/app/main.py
  data-analysis-service/init_db.py
  data-analysis-service/requirements.txt
  docker-compose.yml
  stock-service/pom.xml
  user-service/src/main/java/rs/raf/user_service/bootstrap/BootstrapData.java
Labels: size/XXL, lgtm, approved

#293 Remove jackson from stock service
  stock-service/pom.xml
Labels: lgtm, approved, size/S

#294 Fix kotlin cors
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/configuration/SpringSecurityConfig.kt
Labels: size/XS, lgtm, approved

#295 Fix order sim minimum amount again ??
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
Labels: size/XS, lgtm, approved

#298 Fix order profit and tax (Attempt one)
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OrderServiceTest.java
Labels: lgtm, approved, size/M

#299 Fix order profit and tax (Attempt two) (remove all stock test data)
  bank-service/src/main/resources/application.properties
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/S
