Repository RAF-SI-2024/Banka-3-Backend, pull requests merged in 2025-03, with the labels that each got.

#70 Napravio sta treba za kredite
  bank-service/src/main/java/rs/raf/bank_service/controller/InstallmentController.java
  bank-service/src/main/java/rs/raf/bank_service/controller/LoanController.java
  bank-service/src/main/java/rs/raf/bank_service/controller/LoanRequestController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/CurrencyDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/InstallmentCreateDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/InstallmentDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/LoanDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/LoanRequestDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/LoanShortDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Credit.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/LoanNotFoundException.java
  bank-service/src/main/java/rs/raf/bank_service/mappers/InstallmentMapper.java
  bank-service/src/main/java/rs/raf/bank_service/mappers/LoanMapper.java
  bank-service/src/main/java/rs/raf/bank_service/mappers/LoanRequestMapper.java
  bank-service/src/main/java/rs/raf/bank_service/repository/InstallmentRepository.java
  bank-service/src/main/java/rs/raf/bank_service/repository/LoanRepository.java
  bank-service/src/main/java/rs/raf/bank_service/repository/LoanRequestRepository.java
  bank-service/src/main/java/rs/raf/bank_service/service/InstallmentService.java
  bank-service/src/main/java/rs/raf/bank_service/service/LoanRequestService.java
  bank-service/src/main/java/rs/raf/bank_service/service/LoanService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AccountControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AccountServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/CardControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/InstallmentControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanRequestControllerTest.java
Labels: backend

#101 Create OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#102 Update OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#103 Add test exchange rate data, optimize api calls and disable them for now
  bank-service/src/main/java/rs/raf/bank_service/BankServiceApplication.java
  bank-service/src/main/java/rs/raf/bank_service/bootstrap/BootstrapData.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/ExchangeRate.java
  bank-service/src/main/java/rs/raf/bank_service/service/ExchangeRateService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/ExchangeRateServiceTest.java
Labels: size/L, lgtm, approved

#99 izracunavanje rate
  bank-service/src/main/java/rs/raf/bank_service/exceptions/UnkownLoanTypeException.java
  bank-service/src/main/java/rs/raf/bank_service/repository/LoanRepository.java
  bank-service/src/main/java/rs/raf/bank_service/service/LoanService.java
  bank-service/src/main/java/rs/raf/bank_service/specification/LoanInterestRateCalculator.java
  bank-service/src/main/java/rs/raf/bank_service/specification/LoanRateCalculator.java
  bank-service/src/main/java/rs/raf/bank_service/specification/LoanScheduler.java
Labels: size/L, lgtm, approved

#105 Uradjeno automatsko skidanje rata v2
  bank-service/src/main/java/rs/raf/bank_service/configuration/ScheduleConfig.java
  bank-service/src/main/java/rs/raf/bank_service/controller/LoanController.java
  bank-service/src/main/java/rs/raf/bank_service/controller/LoanRequestController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/LoanRequestDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Installment.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/LoanRequest.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/InvalidEmploymentStatusException.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/InvalidInterestRateTypeException.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/InvalidLoanStatusException.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/InvalidLoanTypeException.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/LoanRequestNotFoundException.java
  bank-service/src/main/java/rs/raf/bank_service/mappers/LoanRequestMapper.java
  bank-service/src/main/java/rs/raf/bank_service/repository/AccountRepository.java
  bank-service/src/main/java/rs/raf/bank_service/repository/LoanRepository.java
  bank-service/src/main/java/rs/raf/bank_service/service/LoanRequestService.java
  bank-service/src/main/java/rs/raf/bank_service/service/LoanService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanRequestControllerTest.java
  email-service/src/main/java/rs/raf/email_service/EmailListener.java
  email-service/src/main/java/rs/raf/email_service/configuration/RabbitMQConfig.java
  email-service/src/main/java/rs/raf/email_service/data/EmailType.java
  email-service/src/main/java/rs/raf/email_service/utils/EmailUtils.java
Labels: lgtm, approved, size/XL

#106 Fix loans and stuff
  bank-service/src/main/java/rs/raf/bank_service/controller/LoanController.java
  bank-service/src/main/java/rs/raf/bank_service/controller/LoanRequestController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/CreateLoanRequestDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/ErrorMessageDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/LoanRequestDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/LoanShortDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/LoanRequest.java
  bank-service/src/main/java/rs/raf/bank_service/domain/mapper/InstallmentMapper.java
  bank-service/src/main/java/rs/raf/bank_service/domain/mapper/LoanMapper.java
  bank-service/src/main/java/rs/raf/bank_service/domain/mapper/LoanRequestMapper.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/GlobalExceptionHandler.java
  bank-service/src/main/java/rs/raf/bank_service/mappers/LoanRequestMapper.java
  bank-service/src/main/java/rs/raf/bank_service/repository/LoanRepository.java
  bank-service/src/main/java/rs/raf/bank_service/repository/LoanRequestRepository.java
  bank-service/src/main/java/rs/raf/bank_service/service/InstallmentService.java
  bank-service/src/main/java/rs/raf/bank_service/service/LoanRequestService.java
  bank-service/src/main/java/rs/raf/bank_service/service/LoanService.java
  bank-service/src/main/java/rs/raf/bank_service/specification/LoanRequestSpecification.java
  bank-service/src/main/java/rs/raf/bank_service/specification/LoanSpecification.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanRequestControllerTest.java
  user-service/pom.xml
Labels: lgtm, approved, size/XL

#107 Add verification request details and createdAt, fix change limit, fix request approval/deny, add request history
  bank-service/src/main/java/rs/raf/bank_service/configuration/SpringSecurityConfig.java
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/ChangeAccountLimitDetailsDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/CreateVerificationRequestDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/PaymentVerificationDetailsDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/ChangeLimitRequest.java
  bank-service/src/main/java/rs/raf/bank_service/repository/ChangeLimitRequestRepository.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AccControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AccServiceTest.java
  user-service/src/main/java/rs/raf/user_service/controller/VerificationRequestController.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/CreateVerificationRequestDto.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/VerificationRequestDto.java
  user-service/src/main/java/rs/raf/user_service/domain/entity/VerificationRequest.java
  user-service/src/main/java/rs/raf/user_service/domain/enums/VerificationStatus.java
  user-service/src/main/java/rs/raf/user_service/repository/VerificationRequestRepository.java
  user-service/src/main/java/rs/raf/user_service/service/VerificationRequestService.java
  user-service/src/test/java/rs/raf/user_service/unit/VerificationRequestServiceTest.java
  user-service/src/test/java/rs/raf/user_service/unit/VerificationRequestTest.java
Labels: approved, size/XL

#100 Menjacnica - Integracija sa placanjem i prenosom (Issue #84)
  bank-service/src/main/java/rs/raf/bank_service/bootstrap/BootstrapData.java
  bank-service/src/main/java/rs/raf/bank_service/controller/ExchangeRateController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/CreateVerificationRequestDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/CurrencyDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/ExchangeRateDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Currency.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/ExchangeRate.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Payment.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/BankAccountNotFoundException.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/GlobalExceptionHandler.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/InvalidExchangeRateException.java
  bank-service/src/main/java/rs/raf/bank_service/repository/AccountRepository.java
  bank-service/src/main/java/rs/raf/bank_service/service/ExchangeRateService.java
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/ControllerExchangeRatesUnitTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/ExchangeRateServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/ServiceExchangeRatesUnitTest.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/CreateClientDto.java
Labels: lgtm, approved, size/XL

#104 Integracioni test
  bank-service/pom.xml
  bank-service/src/main/java/rs/raf/bank_service/client/UserClient.java
  bank-service/src/main/java/rs/raf/bank_service/client/UserClientFallbackFactory.java
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/ActivationRequestDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/CreateClientDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/LoginRequestDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/LoginResponseDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Account.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Payment.java
  bank-service/src/test/java/rs/raf/bank_service/cucumber/CucumberSpringConfiguration.java
  bank-service/src/test/java/rs/raf/bank_service/integration/BankServiceTestsConfig.java
  bank-service/src/test/java/rs/raf/bank_service/integration/BankServiceTestsIT.java
  bank-service/src/test/java/rs/raf/bank_service/integration/BankServiceTestsSteps.java
  bank-service/src/test/resources/features/integration/bankservice/bank-service.feature
  bank-service/src/test/resources/features/integration/bankservice/email-send.feature
  pom.xml
  user-service/pom.xml
  user-service/src/main/java/rs/raf/user_service/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/raf/user_service/domain/entity/AuthToken.java
  user-service/src/main/java/rs/raf/user_service/service/ClientService.java
  user-service/src/main/java/rs/raf/user_service/service/EmployeeService.java
  user-service/src/test/java/rs/raf/user_service/unit/ClientServiceTest.java
  user-service/src/test/java/rs/raf/user_service/unit/EmployeeServiceTest.java
Labels: lgtm, approved, size/XL

#108 Move payment mapper, add creation timestamp to payment
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Payment.java
  bank-service/src/main/java/rs/raf/bank_service/domain/mapper/PaymentMapper.java
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/PaymentServiceTest.java
Labels: lgtm, approved, size/S

#109 Add loan id to dtos
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/LoanDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/LoanShortDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/mapper/LoanMapper.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanRequestControllerTest.java
Labels: size/XS, lgtm, approved

#124 Adding Jacoco for test coverage
  pom.xml
Labels: lgtm, approved, size/M

#126 Check if sender account is owned by client on payment/transfer creation
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentService.java
Labels: size/XS, lgtm, approved

#129 order entity
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/OrderDirection.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/OrderStatus.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/OrderType.java
Labels: lgtm, approved, size/M

#130 Fix changing account name, add role to UpdateEmployee, remove admin auth from making payments
  bank-service/src/main/java/rs/raf/bank_service/controller/PaymentController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/AccountDetailsDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/AccountDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/CompanyAccountDetailsDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/NewBankAccountDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Account.java
  bank-service/src/main/java/rs/raf/bank_service/domain/mapper/AccountMapper.java
  bank-service/src/main/java/rs/raf/bank_service/repository/AccountRepository.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  user-service/src/main/java/rs/raf/user_service/controller/EmployeeController.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/CreateEmployeeDto.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/EmployeeDto.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/UpdateEmployeeDto.java
  user-service/src/main/java/rs/raf/user_service/domain/entity/BaseUser.java
  user-service/src/main/java/rs/raf/user_service/domain/entity/Employee.java
  user-service/src/main/java/rs/raf/user_service/domain/mapper/EmployeeMapper.java
  user-service/src/main/java/rs/raf/user_service/exceptions/RoleNotFoundException.java
  user-service/src/main/java/rs/raf/user_service/service/EmployeeService.java
  user-service/src/test/java/rs/raf/user_service/integration/userservice/services/UserServiceTestsSteps.java
  user-service/src/test/java/rs/raf/user_service/unit/EmployeeControllerTest.java
  user-service/src/test/java/rs/raf/user_service/unit/EmployeeServiceTest.java
  user-service/src/test/resources/features/integration/userservice/services.feature
Labels: size/L, lgtm, approved

#134 Move Authorized personnel CRUD to employees, add loan bootstrap data
  bank-service/src/main/java/rs/raf/bank_service/bootstrap/BootstrapData.java
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  user-service/src/main/java/rs/raf/user_service/controller/AuthorizedPersonelController.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/AuthorizedPersonelDto.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/CreateAuthorizedPersonelDto.java
  user-service/src/main/java/rs/raf/user_service/domain/entity/AuthorizedPersonel.java
  user-service/src/main/java/rs/raf/user_service/service/AuthorizedPersonelService.java
  user-service/src/test/java/rs/raf/user_service/unit/AuthorizedPersonelControllerTest.java
  user-service/src/test/java/rs/raf/user_service/unit/AuthorizedPersonelServiceTest.java
Labels: size/L, lgtm, approved

#133 Uradjen portal za upravljanje aktuarima
  user-service/src/main/java/rs/raf/user_service/UserServiceApplication.java
  user-service/src/main/java/rs/raf/user_service/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/raf/user_service/controller/ActuaryController.java
  user-service/src/main/java/rs/raf/user_service/controller/UserController.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/ChangeAgentLimitDto.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/SetApprovalDto.java
  user-service/src/main/java/rs/raf/user_service/domain/entity/ActuaryLimit.java
  user-service/src/main/java/rs/raf/user_service/exceptions/ActuaryLimitNotFoundException.java
  user-service/src/main/java/rs/raf/user_service/exceptions/ClientCannotBeAgentException.java
  user-service/src/main/java/rs/raf/user_service/exceptions/EmployeeNotFoundException.java
  user-service/src/main/java/rs/raf/user_service/exceptions/UserNotAgentException.java
  user-service/src/main/java/rs/raf/user_service/repository/ActuaryLimitRepository.java
  user-service/src/main/java/rs/raf/user_service/service/ActuaryService.java
  user-service/src/main/java/rs/raf/user_service/service/UserService.java
  user-service/src/main/java/rs/raf/user_service/specification/EmployeeSearchSpecification.java
  user-service/src/test/java/rs/raf/user_service/unit/ActuaryControllerTest.java
  user-service/src/test/java/rs/raf/user_service/unit/ActuaryServiceTest.java
Labels: lgtm, approved, size/XL

#136 Prebacena role logika za agenta iz userservice-a u employeeservice
  user-service/src/main/java/rs/raf/user_service/controller/UserController.java
  user-service/src/main/java/rs/raf/user_service/service/EmployeeService.java
  user-service/src/main/java/rs/raf/user_service/service/UserService.java
Labels: lgtm, approved, size/M

#138 Refactor + Fixes
  bank-service/src/main/java/rs/raf/bank_service/client/UserClient.java
  bank-service/src/main/java/rs/raf/bank_service/client/UserClientFallbackFactory.java
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/AuthorizedPersonelDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/ClientDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/CompanyAccountDetailsDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Account.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/CompanyAccount.java
  bank-service/src/main/java/rs/raf/bank_service/domain/mapper/AccountMapper.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/AuthorizedPersonNotFoundException.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/InvalidAuthorizedPersonException.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/PurposeOfPaymentNotProvidedException.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/UnathorizedPersonException.java
  bank-service/src/main/java/rs/raf/bank_service/exceptions/UnauthorizedException.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  bank-service/src/main/java/rs/raf/bank_service/service/ExchangeRateService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AccControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AccServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AuthorizedPersonServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/ServiceExchangeRatesUnitTest.java
  user-service/src/main/java/rs/raf/user_service/controller/AuthorizedPersonelController.java
  user-service/src/main/java/rs/raf/user_service/controller/CompanyController.java
  user-service/src/main/java/rs/raf/user_service/controller/EmployeeController.java
  user-service/src/main/java/rs/raf/user_service/service/AuthorizedPersonelService.java
  user-service/src/main/java/rs/raf/user_service/service/ClientService.java
  user-service/src/main/java/rs/raf/user_service/specification/EmployeeSearchSpecification.java
  user-service/src/test/java/rs/raf/user_service/unit/AuthorizedPersonelControllerTest.java
  user-service/src/test/java/rs/raf/user_service/unit/AuthorizedPersonelServiceTest.java
Labels: lgtm, approved, size/XL

#141 Add endpoint for getting companies owned by client
  bank-service/src/main/java/rs/raf/bank_service/bootstrap/BootstrapData.java
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/AccountDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/AccountTypeDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/mapper/AccountMapper.java
  user-service/src/main/java/rs/raf/user_service/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/raf/user_service/controller/CompanyController.java
  user-service/src/main/java/rs/raf/user_service/repository/CompanyRepository.java
  user-service/src/main/java/rs/raf/user_service/service/CompanyService.java
  user-service/src/test/java/rs/raf/user_service/unit/CompanyControllerTest.java
Labels: size/L, lgtm, approved

#132 orders list
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OrderDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/OrderStatus.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/OrderStatusNotFoundException.java
  stock-service/src/main/java/rs/raf/stock_service/repository/OrderRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/test/java/unit/OrderServiceTest.java
Labels: size/L, lgtm, approved

#137 Dodati unit testovi
  bank-service/pom.xml
  bank-service/src/test/java/rs/raf/bank_service/unit/AccountControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/CardServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/InstallmentServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanRequestServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanRequestSpecificationTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanSchedulerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanSpecificationTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/PaymentServiceTest.java
  email-service/src/test/java/rs/raf/email_service/unit/EmailListenerTest.java
  user-service/src/test/java/rs/raf/user_service/unit/AuthControllerTest.java
  user-service/src/test/java/rs/raf/user_service/unit/ClientSearchSpecificationTest.java
  user-service/src/test/java/rs/raf/user_service/unit/CompanyServiceTest.java
  user-service/src/test/java/rs/raf/user_service/unit/UserControllerTest.java
  user-service/src/test/java/rs/raf/user_service/unit/UserServiceApplicationTests.java
  user-service/src/test/java/rs/raf/user_service/unit/VerificationRequestControllerTest.java
Labels: size/XXL, lgtm, approved

#144 Return created company dto on create, add more activty codes.
  pom.xml
  user-service/src/main/java/rs/raf/user_service/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/raf/user_service/controller/CompanyController.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/CompanyDto.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/CreateCompanyDto.java
  user-service/src/main/java/rs/raf/user_service/domain/mapper/CompanyMapper.java
  user-service/src/main/java/rs/raf/user_service/service/CompanyService.java
  user-service/src/test/java/rs/raf/user_service/unit/CompanyControllerTest.java
Labels: size/L, lgtm, approved

#145 Add client's cards per account endpoint
  bank-service/src/main/java/rs/raf/bank_service/bootstrap/BootstrapData.java
  bank-service/src/main/java/rs/raf/bank_service/controller/CardController.java
  bank-service/src/main/java/rs/raf/bank_service/service/CardService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/CardControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/CardServiceTest.java
Labels: size/L, lgtm, approved

#131 Uradjen GET endpoint za hartije od vrednosti
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/controller/ListingController.java
  stock-service/src/main/java/rs/raf/stock_service/controller/StockOptionController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ListingDetailsDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ListingDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ListingFilterDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ListingUpdateDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/PriceHistoryDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/StockOptionDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Listing.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/ListingType.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/ListingMapper.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/StockOptionMapper.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/GlobalExceptionHandler.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/ListingNotFoundException.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/UnauthorizedException.java
  stock-service/src/main/java/rs/raf/stock_service/repository/ExchangeRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/ListingDailyPriceInfoRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/ListingRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/OptionRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/ListingService.java
  stock-service/src/main/java/rs/raf/stock_service/service/StockOptionService.java
  stock-service/src/main/java/rs/raf/stock_service/specification/ListingSpecification.java
  stock-service/src/main/java/rs/raf/stock_service/utils/JwtTokenUtil.java
  stock-service/src/test/java/rs/raf/stock_service/unit/ListingControllerTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/ListingServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/StockOptionControllerTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/StockOptionServiceTest.java
Labels: size/XXL, lgtm, approved

#146 Berze - Prikupljanje Podataka #114 [fix]
  bank-service/pom.xml
  stock-service/pom.xml
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/controller/ExchangeController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/CountryHolidayDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/CountryHolidaysDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Country.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Exchange.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Holiday.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/ExchangesNotLoadedException.java
  stock-service/src/main/java/rs/raf/stock_service/repository/CountryRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/ExchangeRepository.java
  stock-service/src/main/java/rs/raf/stock_service/repository/HolidayRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/CountryService.java
  stock-service/src/main/java/rs/raf/stock_service/service/ExchangeService.java
  stock-service/src/main/java/rs/raf/stock_service/service/HolidayService.java
  stock-service/src/main/resources/exchanges.csv
  stock-service/src/main/resources/holidays.json
  stock-service/src/test/java/rs/raf/stock_service/unit/CountryServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/ExchangeServiceTest.java
Labels: size/XXL, lgtm, approved

#148 Card fixes + add loan request id to dto + add authorizedPersonId to create account dto
  bank-service/src/main/java/rs/raf/bank_service/bootstrap/BootstrapData.java
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/raf/bank_service/controller/CardController.java
  bank-service/src/main/java/rs/raf/bank_service/controller/ExchangeRateController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/CardDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/CardDtoNoOwner.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/CreateCardDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/LoanRequestDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/NewBankAccountDto.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Card.java
  bank-service/src/main/java/rs/raf/bank_service/domain/enums/CardIssuer.java
  bank-service/src/main/java/rs/raf/bank_service/domain/mapper/CardMapper.java
  bank-service/src/main/java/rs/raf/bank_service/domain/mapper/LoanRequestMapper.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  bank-service/src/main/java/rs/raf/bank_service/service/CardService.java
  bank-service/src/test/java/rs/raf/bank_service/integration/BankServiceTestsSteps.java
  bank-service/src/test/java/rs/raf/bank_service/unit/CardControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/CardServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanRequestControllerTest.java
  user-service/src/main/java/rs/raf/user_service/controller/ClientController.java
  user-service/src/main/java/rs/raf/user_service/controller/EmployeeController.java
Labels: size/L, lgtm, approved

#149 Fix verification request history query
  user-service/src/main/java/rs/raf/user_service/controller/VerificationRequestController.java
  user-service/src/main/java/rs/raf/user_service/repository/VerificationRequestRepository.java
  user-service/src/main/java/rs/raf/user_service/service/VerificationRequestService.java
  user-service/src/test/java/rs/raf/user_service/unit/VerificationRequestControllerTest.java
Labels: lgtm, approved, size/M

#143 Demployment svih servisa na Docker
  bank-service/Dockerfile
  bank-service/pom.xml
  bank-service/src/main/java/rs/raf/bank_service/client/UserClient.java
  bank-service/src/main/resources/application.properties
  docker-compose.prod.yml
  docker-compose.yml
  email-service/Dockerfile
  email-service/pom.xml
  stock-service/Dockerfile
  stock-service/pom.xml
  user-service/Dockerfile
  user-service/pom.xml
  user-service/src/main/java/rs/raf/user_service/client/BankClient.java
  user-service/src/main/resources/application.properties
Labels: size/L, lgtm, approved

#151 Docker compose deployment merge + add tests
  bank-service/Dockerfile
  bank-service/pom.xml
  bank-service/src/main/java/rs/raf/bank_service/client/UserClient.java
  bank-service/src/main/resources/application.properties
  bank-service/src/test/java/rs/raf/bank_service/unit/PaymentServiceTest.java
  docker-compose.prod.yml
  docker-compose.yml
  email-service/Dockerfile
  email-service/pom.xml
  stock-service/Dockerfile
  stock-service/pom.xml
  user-service/Dockerfile
  user-service/pom.xml
  user-service/src/main/java/rs/raf/user_service/client/BankClient.java
  user-service/src/main/java/rs/raf/user_service/domain/entity/Employee.java
  user-service/src/main/resources/application.properties
Labels: lgtm, approved, size/XL

#154 KT2 Fixes
  bank-service/src/main/java/rs/raf/bank_service/client/UserClient.java
  bank-service/src/main/java/rs/raf/bank_service/client/UserClientFallbackFactory.java
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/NewBankAccountDto.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  bank-service/src/main/java/rs/raf/bank_service/service/CardService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AccountServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/CardServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanServiceTest.java
  user-service/src/main/java/rs/raf/user_service/controller/VerificationRequestController.java
  user-service/src/test/java/rs/raf/user_service/unit/VerificationRequestControllerTest.java
Labels: lgtm, approved, size/XL

#155 Create pull_request_template.md
  pull_request_template.md
Labels: lgtm, approved, size/S

#165 Fix setting balances on payment/transfer/loan #156
  bank-service/src/main/java/rs/raf/bank_service/service/LoanRequestService.java
  bank-service/src/main/java/rs/raf/bank_service/service/PaymentService.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanRequestServiceTest.java
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/controller/ListingController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Listing.java
  stock-service/src/main/java/rs/raf/stock_service/specification/ListingSpecification.java
Labels: size/L, lgtm, approved

#166 Uradjeno kreiranje i approve/deny ordera
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/client/UserClient.java
  stock-service/src/main/java/rs/raf/stock_service/controller/ListingController.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ActuaryLimitDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/BuyListingDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ListingDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OrderDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/OrderNotFoundException.java
  stock-service/src/main/java/rs/raf/stock_service/service/ListingService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/main/resources/application.properties
  stock-service/src/test/java/unit/ListingControllerTest.java
  stock-service/src/test/java/unit/OrderControllerTest.java
  stock-service/src/test/java/unit/OrderServiceTest.java
  user-service/src/main/java/rs/raf/user_service/controller/ActuaryController.java
  user-service/src/main/java/rs/raf/user_service/domain/dto/ActuaryLimitDto.java
  user-service/src/main/java/rs/raf/user_service/service/ActuaryService.java
Labels: size/L, lgtm, approved

#167 fixovan prosli pr
  docker-compose.prod.yml
  stock-service/src/main/java/rs/raf/stock_service/controller/ListingController.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/ActuaryLimitDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/BuyListingDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/AccountType.java
  stock-service/src/main/java/rs/raf/stock_service/exceptions/CantApproveNonPendingOrder.java
  stock-service/src/main/java/rs/raf/stock_service/service/ListingService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/test/java/unit/ListingServiceTest.java
  stock-service/src/test/java/unit/OrderServiceTest.java
Labels: size/L, lgtm, approved

#169 bank-service unit testovi
  bank-service/src/test/java/rs/raf/bank_service/unit/AccControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AccServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AccountControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AccountServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/AuthorizedPersonServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/CardControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/CardServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/ControllerExchangeRatesUnitTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/ExchangeRateControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/ExchangeRateServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/InstallmentControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/InstallmentServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanRequestControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanRequestServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanRequestSpecificationTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanSchedulerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanSpecificationTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/PayeeControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/PaymentControllerTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/PaymentServiceTest.java
  bank-service/src/test/java/rs/raf/bank_service/unit/ServiceExchangeRatesUnitTest.java
Labels: size/XXL, lgtm, approved

#172 Implementacija i izvrsenje market order
  bank-service/src/main/java/rs/raf/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/raf/bank_service/service/AccountService.java
  docker-compose.prod.yml
  stock-service/src/main/java/rs/raf/stock_service/StockServiceApplication.java
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClient.java
  stock-service/src/main/java/rs/raf/stock_service/configuration/AsyncConfig.java
  stock-service/src/main/java/rs/raf/stock_service/controller/ListingController.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/CreateOrderDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OrderDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/TransactionDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Transaction.java
  stock-service/src/main/java/rs/raf/stock_service/domain/enums/OrderStatus.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OrderMapper.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/TransactionMapper.java
  stock-service/src/main/java/rs/raf/stock_service/repository/TransactionRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/ListingService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/main/resources/application.properties
  stock-service/src/test/java/rs/raf/stock_service/unit/FuturesServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OptionServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OrderServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/StocksServiceApplicationTests.java
  stock-service/src/test/java/unit/ListingControllerTest.java
  stock-service/src/test/java/unit/ListingServiceTest.java
  stock-service/src/test/java/unit/OrderControllerTest.java
  stock-service/src/test/java/unit/OrderServiceTest.java
Labels: size/XXL, lgtm, approved

#174 Loan fixes
  bank-service/src/main/java/rs/raf/bank_service/controller/LoanRequestController.java
  bank-service/src/main/java/rs/raf/bank_service/service/TransactionProcessor.java
  bank-service/src/main/java/rs/raf/bank_service/service/TransactionQueueService.java
  bank-service/src/main/java/rs/raf/bank_service/specification/LoanRateCalculator.java
Labels: lgtm, approved, size/S

#186 Fixovanje hartija i price history #179
  stock-service/src/main/java/rs/raf/stock_service/bootstrap/BootstrapData.java
  stock-service/src/main/java/rs/raf/stock_service/client/BankClient.java
  stock-service/src/main/java/rs/raf/stock_service/client/TwelveDataClient.java
  stock-service/src/main/java/rs/raf/stock_service/configuration/SpringSecurityConfig.java
  stock-service/src/main/java/rs/raf/stock_service/controller/ListingController.java
  stock-service/src/main/java/rs/raf/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OptionDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/OrderDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/TimeSeriesDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Transaction.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OrderMapper.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/TimeSeriesMapper.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/TransactionMapper.java
  stock-service/src/main/java/rs/raf/stock_service/repository/TransactionRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/ForexService.java
  stock-service/src/main/java/rs/raf/stock_service/service/ListingService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OptionService.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/main/java/rs/raf/stock_service/specification/ListingSpecification.java
  stock-service/src/test/java/rs/raf/stock_service/unit/ListingServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/OrderServiceTest.java
  stock-service/src/test/java/rs/raf/stock_service/unit/StocksServiceApplicationTests.java
Labels: size/L, lgtm, approved

#183 Moj portfolio #163
  docker-compose.yml
  email-service/src/main/resources/application.properties
  stock-service/src/main/java/rs/raf/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/raf/stock_service/controller/PortfolioController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/dto/PortfolioEntryDto.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Listing.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/ListingDailyPriceInfo.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/PortfolioEntry.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Stock.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/PortfolioMapper.java
  stock-service/src/main/java/rs/raf/stock_service/repository/PortfolioEntryRepository.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
  stock-service/src/main/resources/application.properties
  stock-service/src/test/java/unit/PortfolioServiceTest.java
  user-service/src/main/resources/application.properties
Labels: lgtm, approved, size/XL

#188 Integration test fix.
  bank-service/src/main/java/rs/raf/bank_service/repository/CardRequestRepository.java
  bank-service/src/test/java/rs/raf/bank_service/integration/BankServiceTestsSteps.java
  bank-service/src/test/resources/features/integration/bankservice/bank-service.feature
  user-service/src/main/java/rs/raf/user_service/bootstrap/BootstrapData.java
Labels: size/L, lgtm, approved

#185 ispravljeno sta je trebalo za loans
  bank-service/src/main/java/rs/raf/bank_service/controller/LoanController.java
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/Loan.java
  bank-service/src/main/java/rs/raf/bank_service/domain/mapper/LoanMapper.java
  bank-service/src/main/java/rs/raf/bank_service/service/LoanService.java
  bank-service/src/main/java/rs/raf/bank_service/specification/LoanScheduler.java
  bank-service/src/test/java/rs/raf/bank_service/unit/LoanServiceTest.java
Labels: size/L, lgtm, approved
