Repository RAF-SI-2024/Banka-3-Backend, pull requests merged in 2025-06, with the labels that each got.

#304 Fix precision in bigdecimal columns
  bank-service/src/main/java/rs/raf/bank_service/domain/entity/ExchangeRate.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/ForexPair.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/FuturesContract.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Listing.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/ListingPriceHistory.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Order.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/OtcOffer.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/OtcOption.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/PortfolioEntry.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Stock.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/Transaction.java
Labels: lgtm, approved, size/M

#305 Add more logs
  bank-service/src/main/java/rs/raf/bank_service/controller/ExchangeRateController.java
  stock-service/src/main/java/rs/raf/stock_service/domain/entity/TrackedPayment.java
  stock-service/src/main/java/rs/raf/stock_service/service/OrderService.java
Labels: lgtm, approved, size/S

#306 Add more logs, fix order afterHours column
  bank-service/src/main/java/rs/raf/bank_service/domain/dto/PaymentDetailsDto.java
  bank-service/src/main/java/rs/raf/bank_service/service/TransactionProcessor.java
  stock-service/src/main/java/rs/raf/stock_service/domain/mapper/OrderMapper.java
Labels: lgtm, approved, size/S

#308 Fix reservedAmount update on simulated sell (not all or none)
  stock-service/src/main/java/rs/raf/stock_service/service/PortfolioService.java
Labels: size/XS, lgtm, approved

#309 Fix routes
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/AuthController.kt
Labels: size/XS, lgtm, approved

#310 Add kotlin user creation error handling + temp disable exchange rates update
  bank-service/src/main/java/rs/raf/bank_service/service/ExchangeRateService.java
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/arrow/ClientServiceError.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/arrow/EmployeeServiceError.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/ClientController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/controller/EmployeeController.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/repository/ClientRepository.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/repository/EmployeeRepository.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/service/ClientService.kt
  user-service-kotlin/src/main/kotlin/pack/userservicekotlin/service/EmployeeService.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/controller/ClientControllerTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/controller/EmployeeControllerTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/service/ClientServiceTest.kt
  user-service-kotlin/src/test/kotlin/pack/userservicekotlin/service/EmployeeServiceTest.kt
Labels: lgtm, approved, size/M
